# Generated by Django 3.0.9 on 2020-08-24 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentName', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50)),
                ('equipType', models.CharField(max_length=50)),
                ('equipSemiType', models.CharField(default='', max_length=50)),
                ('isExist', models.BooleanField(default=True)),
                ('willBorrow', models.CharField(default=False, max_length=50)),
                ('Borrow', models.CharField(default=False, max_length=50)),
                ('Borrowed', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studioName', models.CharField(max_length=50)),
                ('studioType', models.CharField(max_length=50)),
                ('isExist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDate', models.CharField(max_length=50)),
                ('toDateTime', models.CharField(max_length=50)),
                ('fromDate', models.CharField(max_length=50)),
                ('fromDateTime', models.CharField(max_length=50)),
                ('realDate', models.CharField(default=0, max_length=50)),
                ('realDateTime', models.CharField(default=0, max_length=50)),
                ('division', models.CharField(default='', max_length=50)),
                ('goal', models.CharField(default='', max_length=50)),
                ('isCard', models.BooleanField(default=False)),
                ('willBorrow', models.CharField(default=False, max_length=50)),
                ('Borrow', models.CharField(default=False, max_length=50)),
                ('Borrowed', models.CharField(default=False, max_length=50)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sborrow', to='app.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAuth', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=200)),
                ('toDate', models.CharField(max_length=50)),
                ('toDateTime', models.IntegerField(max_length=50)),
                ('fromDate', models.CharField(max_length=50)),
                ('fromDateTime', models.IntegerField(max_length=50)),
                ('realDate', models.CharField(default=0, max_length=50)),
                ('realDateTime', models.IntegerField(default=0, max_length=50)),
                ('group', models.CharField(default='', max_length=50)),
                ('purpose', models.CharField(default='', max_length=50)),
                ('auth', models.CharField(default='', max_length=50)),
                ('remark', models.CharField(default='', max_length=50)),
                ('willBorrow', models.CharField(default=False, max_length=50)),
                ('Borrow', models.CharField(default=False, max_length=50)),
                ('Borrowed', models.CharField(default=False, max_length=50)),
                ('uesr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Euser', to='app.Profile')),
            ],
        ),
    ]
