# Generated by Django 3.0.9 on 2020-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200824_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipSemiType',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
