# Generated by Django 3.1 on 2020-08-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200807_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='penalty',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isAuth',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
